# Generated by Django 5.0.1 on 2024-05-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='read_more_link',
            field=models.URLField(blank=True),
        ),
    ]
