# Generated by Django 5.0.1 on 2024-05-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0003_remove_aboutus_read_more_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
