# Generated by Django 5.0.1 on 2024-05-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
