# Generated by Django 5.0.1 on 2024-05-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='link',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='read_more_link',
            field=models.URLField(blank=True),
        ),
    ]
