# Generated by Django 5.0.1 on 2024-05-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0008_remove_aboutus_link_aboutus_read_more_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='read_more_link',
        ),
    ]
