# Generated by Django 5.0.1 on 2024-05-07 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutus.aboutus')),
            ],
        ),
    ]
