# Generated by Django 5.0.1 on 2024-05-08 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='about_us',
        ),
    ]
