# Generated by Django 5.0.1 on 2024-05-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_home_about_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
