# Generated by Django 5.0.1 on 2024-05-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_reservation_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
