# Generated by Django 5.0.1 on 2024-05-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_reservation_phone_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
