# Generated by Django 5.0.1 on 2024-05-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
