# Generated by Django 5.0.1 on 2024-05-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='job_type',
            field=models.CharField(max_length=100),
        ),
    ]
