# Generated by Django 5.0.1 on 2024-06-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuItems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinein',
            name='name',
            field=models.CharField(default='Saad', max_length=200),
        ),
    ]
